In [28]:
from numpy.random import seed
from numpy.random import randint
import numpy as np
import time
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
#Begin with the base code for recursion (factorial) as described in 
#chapter 3 of Grokking Algorithms (Bhargava 2016).

def fact(x):
    if x == 1:
        return 1
    else:
        return x * fact(x-1)

In [60]:
#Set up an array of ten random numbers between 100 and 500 (just one array with 10 numbers).

seed(7769)
myArray = randint(100, 500, 10)

# Splitting array into separate objects

print(myArray)

[449 355 303 112 197 248 468 236 277 214]

In [61]:
#Move array values into separate objects for passing to the function
a0 = 449
a1 = 335
a2 = 303
a3 = 112
a4 = 197
a5 = 248
a6 = 468
a7 = 236
a8 = 277
a9 = 214

In [67]:
#Calculate the factorial of each of the numbers using recursion 
#and capture start/end time, store the results in an array, 
#or linked list, or dictionary

start = time.clock()
fact(a0)
stop = time.clock()
a0time = stop - start

start = time.clock()
fact(a1)
stop = time.clock()
a1time = stop - start

start = time.clock()
fact(a2)
stop = time.clock()
a2time = stop - start

start = time.clock()
fact(a3)
stop = time.clock()
a3time = stop - start

start = time.clock()
fact(a4)
stop = time.clock()
a4time = stop - start

start = time.clock()
fact(a5)
stop = time.clock()
a5time = stop - start

start = time.clock()
fact(a6)
stop = time.clock()
a6time = stop - start

start = time.clock()
fact(a7)
stop = time.clock()
a7time = stop - start

start = time.clock()
fact(a8)
stop = time.clock()
a8time = stop - start

start = time.clock()
fact(a9)
stop = time.clock()
a9time = stop - start

aTimes = {'a0' : round(a0time,6), 'a1' : round(a1time,6), 'a2' : round(a2time,6),
         'a3' : round(a3time,6), 'a4' : round(a4time,6), 'a5' : round(a5time,6),
         'a6' : round(a6time,6), 'a7' : round(a7time,6), 'a8' : round(a8time,6),
         'a9' : round(a9time,6)}
aTimes

{'a0': 0.000587,
 'a1': 0.000246,
 'a2': 0.000198,
 'a3': 0.000194,
 'a4': 0.000144,
 'a5': 0.00019,
 'a6': 0.000436,
 'a7': 0.000316,
 'a8': 0.000364,
 'a9': 0.000323}

In [74]:
#Calculate factorial using simple FOR loop and capture start/end time, 
#store the results in an array, or linked list, or dictionary

start = time.clock()
num = a0
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop0time = stop - start

start = time.clock()
num = a1
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop1time = stop - start

start = time.clock()
num = a2
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop2time = stop - start

start = time.clock()
num = a3
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop3time = stop - start

start = time.clock()
num = a4
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop4time = stop - start

start = time.clock()
num = a5
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop5time = stop - start

start = time.clock()
num = a6
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop6time = stop - start

start = time.clock()
num = a7
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop7time = stop - start

start = time.clock()
num = a8
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop8time = stop - start

start = time.clock()
num = a9
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
stop = time.clock()
loop9time = stop - start

loopTimes = {'loop0' : round(loop0time,6), 'loop1' : round(loop1time,6), 
             'loop2' : round(loop2time,6),
         'loop3' : round(loop3time,6), 'loop4' : round(loop4time,6), 
             'loop5' : round(loop5time,6),
         'loop6' : round(loop6time,6), 'loop7' : round(loop7time,6), 
             'loop8' : round(loop8time,6),
         'loop9' : round(loop9time,6)}
loopTimes

{'loop0': 0.001314,
 'loop1': 0.000502,
 'loop2': 0.000432,
 'loop3': 0.000328,
 'loop4': 0.000373,
 'loop5': 0.000438,
 'loop6': 0.000618,
 'loop7': 0.00041,
 'loop8': 0.00046,
 'loop9': 0.00038}

In [114]:
#Organize the results of the study into a table showing the number,
#it's factorial, the time to calculate the factorial using recursion, 
#the time to calculate factorial using FOR loop, and the difference 
#between times i.e. factorial vs. loop.
from decimal import Decimal

myResults = pd.DataFrame(
                        [[a0, "{:.2e}".format(Decimal(fact(a0))), a0time, loop0time],
                         [a1, "{:.2e}".format(Decimal(fact(a1))), a1time, loop1time],
                         [a2, "{:.2e}".format(Decimal(fact(a2))), a2time, loop2time],
                         [a3, "{:.2e}".format(Decimal(fact(a3))), a3time, loop3time],
                         [a4, "{:.2e}".format(Decimal(fact(a4))), a4time, loop4time],
                         [a5, "{:.2e}".format(Decimal(fact(a5))), a5time, loop5time],
                         [a6, "{:.2e}".format(Decimal(fact(a6))), a6time, loop6time],
                         [a7, "{:.2e}".format(Decimal(fact(a7))), a7time, loop7time],
                         [a8, "{:.2e}".format(Decimal(fact(a8))), a8time, loop8time],
                         [a9, "{:.2e}".format(Decimal(fact(a9))), a9time, loop9time]],
columns = ['Number', 'Factorial', 'Calculation Time (Recursion)',
                          'Calculation Time (For-Loop)'])
myResults['RunTime Difference (Loop - Recursion)'] = myResults['Calculation Time (For-Loop)'] - myResults['Calculation Time (Recursion)']
myResults

,Number,Factorial,Calculation Time (Recursion),Calculation Time (For-Loop),RunTime Difference (Loop - Recursion)
0,449,3.85e+997,0.000587,0.001314,0.000727
1,335,1.16e+702,0.000246,0.000502,0.000256
2,303,8.43e+621,0.000198,0.000432,0.000234
3,112,1.97e+182,0.000194,0.000328,0.000134
4,197,1.00e+368,0.000144,0.000373,0.000229
5,248,5.19e+487,0.000190,0.000438,0.000248
6,468,1.44e+1048,0.000436,0.000618,0.000182
7,236,1.26e+459,0.000316,0.000410,0.000094
8,277,7.72e+557,0.000364,0.000460,0.000096
9,214,2.16e+407,0.000323,0.000380,0.000057